[web]
172.31.4.99

[localhost]
localhost

[localhost:vars]

Course="devops with aws"
Trainer="rajesh"
Duration="120hrs"
wishes="morning from inventory"


[db]
172.31.4.99
[app]
3.235.153.154
172.31.4.200
172.31.4.201